In [3]:
import numpy as np


**Basic inspection commands**

In [27]:
a = np.zeros((3,4))
print(f"a = {a}")
print(f"shape = {a.shape}")
print(f"len = {len(a)}")
print(f"number of array dimension = {a.ndim}")
print(f"number of array elements = {a.size}")
print(f"data type = {a.dtype}")
print(f"name of datatype = {a.dtype.name}")
print(f"convert to different type (int) = {a.astype(int)}")
print()

a = [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
shape = (3, 4)
len = 3
number of array dimension = 2
number of array elements = 12
data type = float64
name of datatype = float64
convert to different type (int) = [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

